### ISSUE TITLE
Create, edit, delete categories

### ISSUE THREAD

**Issue by loziniak** [jenspfahl/EverydayTasks#11]
I have some tasks that are tough to categorize with default categories, and throwing everything to „others“ is bad option for me. These tasks are : take a bath, call a friend, build a house. And it's only first day of my app use!

It would be great to be able to create categories that suit me. Also nice to have would be edit and delete categories for full control.

**Comment by jenspfahl** [comment]
Agree. At some point i will add this feature.

**Comment by froyglez** [comment]
Hi, I love this app! But I also would like to have these features please!

**Comment by jenspfahl** [comment]
Once i get my current project done i will look into that.

**Comment by froyglez** [comment]
Thank you!

**Comment by jenspfahl** [comment]
This feature is on its way to F-Droid. Still released on Play store. (Version 1.3.0)
