### ISSUE TITLE
Configure week start, system date format

### ISSUE THREAD

**Issue by loziniak** [jenspfahl/EverydayTasks#12]
In Poland week starts on monday, not sunday. It'd be nice to be able to configure that in calendar.

Also, one of date format options could be perhaps taken from system locale?

**Comment by jenspfahl** [comment]
Date formats are taken from the selected language. The app supports currently English and German, so it also only supports date formats for these countries. Would be great if you contribute a Polish [translation](https://github.com/jenspfahl/EverydayTasks/blob/master/TRANSLATE.md), then i can integrate this language and also the date format!
