### ISSUE TITLE
Snooze scheduled task for 1hour, 1day, etc.

### ISSUE THREAD

**Issue by dontlaugh** [jenspfahl/EverydayTasks#14]
First off, thanks for implementing the pinned view, #7 

I'm back with another scheduled task feature request. ☺️

----

It would be great to snooze tasks for an interval. Snoozing a task would ideally:

1. Clear the existing notification if a task is overdue.
2. Schedule a notification in the future, after the snooze interval runs out.

This is a feature in some email clients these days. It's like I can ask the program, "Remind me about this again in an hour".

This is different from the existing "reset progress" feature 🔃. That feature means "skip this task for one interval".

One question with snooze is whether or not it would 1) move the actual due date, or 2) keep the due date, e.g. if a task that was snoozed for 2 hours would still be 2 hours overdue when the next notification arrives. I prefer option 2, but I don't feel too strongly about it.

**Comment by jenspfahl** [comment]
I just saw the notifications library i use does now support notification actions, so i could add a snooze button inside of the notification. To achieve this requires some more changes so it will take a while to implement, but yes, i have also a need for this functionality. I would go for option 2 (keep due date untouched).

**Comment by jenspfahl** [comment]
In v1.2.0

**Comment by dontlaugh** [comment]
Just got the new build. I'll check it out. Thanks again :)
