### ISSUE TITLE
Can't add task/variant via '+' icon -  1.1.0 (10100)

### ISSUE THREAD

**Issue by dariaGirl** [jenspfahl/EverydayTasks#17]
App>' + ' Icon>"New QuickAdd" selected>QuickAdd Task/Variant PopUp>Select option>Ok
Ok button doesn't work. Doesn't add task/variant.
*Also does not display any sub options. Not fixed on phone restart.

Works via 'Tasks' icon though.

**Comment by jenspfahl** [comment]
In the "New QuickAdd" dialog you should first select a task or variant (unfold a group first to see tasks). Then the OK button works. It doesn't work when just a group is selected. Is this what you mean?

**Comment by dariaGirl** [comment]
Yes, i believe for some reason the sub tasks or variants weren't displaying earlier. Thanks.
