### ISSUE TITLE
Can't view task created? - Issue saving?  -  1.1.0 (10100)

### ISSUE THREAD

**Issue by dariaGirl** [jenspfahl/EverydayTasks#18]
I've created a couple tasks, but selecting either Journal/schedule/Tasks nowhere displays my entered tasks.

I am new to this app, so perhaps it's a configuration issue? Where the tasks not saved correctly?

**Comment by jenspfahl** [comment]
After creating new tasks on the "Tasks" page you can use these tasks as templates for actual schedules or journal entries. More information about how to use the app can be found here: https://everydaytasks.jepfa.de/how/

**Comment by dariaGirl** [comment]
Ok. These are now displaying as they should it seems, must have been some sort of glitch this morning with my phone. Thanks.
