### ISSUE TITLE
Option for minutes and hours as repetition units

### ISSUE THREAD

**Issue by RafeeDaBoy** [jenspfahl/EverydayTasks#19]
When creating a new task there's an option for custom repetition schedule. It'd be really useful if there could be an option for a reminder every couple of minutes or hours.
![Screenshot_2022-11-19-11-48-16-42_230a5e89f5ddcb1946786aad6604c3e3](https://user-images.githubusercontent.com/69535896/202836574-d172d795-a71b-4666-882a-9a647dc9c71e.jpg)

**Comment by jenspfahl** [comment]
Hey,
I am actually working on an opportunity to "remind me later" directly from a notification, similar to a snooze function. Is this what you mean? I could imagine adding an option to configure that reminder interval directly in this screen similar to the custom repetition.

**Comment by RafeeDaBoy** [comment]
That sounds perfect!

**Comment by jenspfahl** [comment]
I actually don't see tasks which repeats on an hourly basis. My intention with this app is tracking daily tasks, therefore a day is the finest granularity. Changing this to minutes or hours would oppose the current concept how the app works and how it is implemented and would require a huge effort to change.
As a workaround, there is  the option to create schedules for the same task but for different times. So it is possible to have e.g. schedules for the same task on a day for different times.

**Comment by RafeeDaBoy** [comment]
> As a workaround, there is the option to create schedules for the same task but for different times. So it is possible to have e.g. schedules for the same task on a day for different times.

Thanks a lot for the response! This more or less fits my use case.
