### ISSUE TITLE
Setting a custom interval affects all custom intervals

### ISSUE THREAD

**Issue by fschli** [jenspfahl/EverydayTasks#2]
Setting a custom interval affects all custom intervals, so it's not possible to use different custom intervals on different scheduled tasks.

Steps to reproduce:
1. Go to Schedules and schedule a task with a custom interval.
2. Schedule another task with a different custom interval.
3. Check the interval on the first task.

Version: 1.0.0 via f-droid

**Comment by jenspfahl** [comment]
Thanks for reporting. I could reproduce it and will fix it soon. The custom repetition of the first schedule is actually not changed by the second but is displayed wrong. After closing and reopening the app the values are correct.
