### ISSUE TITLE
[FR] Multiple intervals

### ISSUE THREAD

**Issue by BoboTiG** [jenspfahl/EverydayTasks#22]
Hy there,

First of all, it's a great app, thanks a lot for that :)

Do you plan to add multiple intervals? For instance, I would like to plan "almost-daily" tasks. Example: "Do that thing" on Mondays, Wednesday, and Sunday. Repeat weekly.

For now, I plan several same tasks for each day. It works though.

**Comment by jenspfahl** [comment]
Hey and thank you for praising it. Supporting multiple schedules for a task is a bit difficult to realise, but i receive this wish from more and more people. When I get more time i will try to find a solution for that.

**Comment by BoboTiG** [comment]
The current situation is not so horrible, I can live with it ;)
If in a future you add such a feature, it will be just better, but the app is actually really cool as-is :muscle:

**Comment by jenspfahl** [comment]
Shipped with v1.6.0, see Fixed Schedules
