### ISSUE TITLE
Date Format ISO - YYYY-MM-DD 

### ISSUE THREAD

**Issue by lamyergeier** [jenspfahl/EverydayTasks#27]
May you please add ISO date Format?

**Comment by jenspfahl** [comment]
The app uses the default date format of your selected language. Your can also change the format details and the language in the settings. 
Do you need ISO format only for the CSV export? In the app itself i would not use the long ISO format, since there are options to tweak it.

**Comment by lamyergeier** [comment]
![Screenshot_20230630_072819](https://github.com/jenspfahl/EverydayTasks/assets/42092626/1b177e98-41fe-49b1-aa8c-6c5c30d65402)


I have language set as English, and we can see that there is no ISO date Format. I was hoping for yyyy-MM-dd

**Comment by jenspfahl** [comment]
Yes, this will come with version 1.4.0. 😉
It is still on F-Droid but not yet on Google Play.
