### ISSUE TITLE
[DE] strange behaviour using schedules,  in version 1.3.0 (10300)

### ISSUE THREAD

**Issue by Landorlin** [jenspfahl/EverydayTasks#28]
Wenn man einen neuen Zeitplan erstellt kommt die erste Erinnerung nicht am Tag der Erstellung sondern nach dem ersten intervall. 

Z.b.: ich erstelle das Ereignis "kinder abholen" jeden freitag nachmittags. Wenn ich dabei den aktuellen bzw nächsten freitag eingebe, kommt die erste Benachrichtigung eine Woche später. Möchte ich den nächsten freitag schon erinnert werden, muss ich den start des Zeitplans benutzerdefiniert vom ersten Zeitpunkt eine woche vorher setzen.

Das ist uninuitiv und wahrscheinlich nicht gewünscht. Vor allem bei langen Intervallen auch schwierig und kann schnell dazu führen,  dass man den ersten Termin verschusselt. Wenn der Zeitplan einmal läuft ist natürlich alles bestens. 

P.s: finde das Programm sonst toll und werde es fix weiter nutzen. (patchworkfamilie mit 2 Kindern die wechseln und einem das bleibt... 😀)

**Comment by jenspfahl** [comment]
Danke für dein wertvolles Feedback!
In der Tat war die Idee, dass die erste Erinnerung erst nach dem ersten Intervall ab Startdatum kommt. Intern ist das Startdatum der Wert der für die nächste Erinnerung verwendet wird (Startdatum + Intervall). Aber ich sehe ein, dass das eher unintuitiv ist. 
Ich könnte das entsprechend deines Vorschlages anpassen. Nur wenn das ausgewählte Startdatum in der Vergangenheit liegt, würde erst nach dem Intervall erinnert werden.

**Comment by Landorlin** [comment]
Bei adhoc Sachen, die man jetzt macht und dann für die Zukunft plant macht das bisherige irgendwie Sinn. Wenn man halt Termine für die Zukunft plant nicht mehr. Dann erwartet man, dass das Startdatum der Zeitpunkt des ersten Ausführens ist.

Ich glaube es ist empfehlenswert es zu ändern,  es wird die Benutzerfreundlichkeit verbessern, v.a. für neue User.

**Comment by jenspfahl** [comment]
In V1.4.0
