### ISSUE TITLE
Transfere Data

### ISSUE THREAD

**Issue by nudeldudel** [jenspfahl/EverydayTasks#3]
I want to ask for a feature for importing / exporting Data. I am a fan of RAML and I wish to support you on this way. 

By trasfering data of taks via API in json-format, it should be possible to integrate Simple-Taks, GTD, Pomodoro and so on into the concept of your App. 

But I am not a programmer, and I don't know, how difficult it is, to implement an API sync into the app. May be, you are interested and find a simple, safe an stable way to work together.

**Comment by jenspfahl** [comment]
Hi! With v1.1 I provide the opportunity to export all journal data as CSV file. A way to import data from somewhere else is not planned. I want to keep the App as simple as possible.
