### ISSUE TITLE
Feature Request: Daily/Weekly/Monthly overview of scheduled tasks

### ISSUE THREAD

**Issue by SnoopAir** [jenspfahl/EverydayTasks#32]
First of all: A big thanks for this great app. A lot of people might argue: Why schedule trivial everyday tasks? I love it.

What I'm missing is an overview on what is scheduled for today, or this week or month with the possibility to filter for specific categories/event types.

Would it be possible to add such overview pages?

**Comment by jenspfahl** [comment]
Hi and thank you for your praise.
This is actually a good idea. I also think it would help to have a powerful filter for the schedules like you proposed. I'll consider this for the next releases.

**Comment by SnoopAir** [comment]
Thank you Jens for the super quick reply, not used to that. For me the more important part of my request was to have a page showing a day/week/month to see which ordinary things are on my agenda so that I can "mentally" prepare for the day/week.

**Comment by jenspfahl** [comment]
So something like a calendar?

**Comment by SnoopAir** [comment]
Yes, just like in any planing tool (even in Outlook or teams) - just nicer; like the rest of your design which I really like

**Comment by jenspfahl** [comment]
A calendar view has been integrated within the latest version to see all schedules daily, weekly or monthly.

**Comment by loziniak** [comment]
A little similar to #13 .
