### ISSUE TITLE
Possibility to customize the letteral time

### ISSUE THREAD

**Issue by serrq** [jenspfahl/EverydayTasks#36]
I like "in the morning", "at noon", etc letteral time: however I need to customize these parameters.

For example I would like to set "in the morning" time at 9 o'clock.

Also I wish the possibility to add (or remove) a totally new one by myself.

**Comment by jenspfahl** [comment]
I'll look into customizing the existing daytime words.

**Comment by jenspfahl** [comment]
Shipped with v1.6.0, in the settings
