### ISSUE TITLE
can't create a backup file

### ISSUE THREAD

**Issue by myf9832** [jenspfahl/EverydayTasks#37]
1 click create a backup file
2 select a folder in internal
3 click allow

expect:create success
actual:can't export database
![Screenshot_2024-01-05-13-26-52-311_de jepfa personaltasklogger](https://github.com/jenspfahl/EverydayTasks/assets/46832911/1975e528-378c-4519-bf77-99805446e583)

**Comment by loziniak** [comment]
> Try to choose "download" as destination path

I also had a success with "Documents". Then there's no problem with copying the file to other folder using file manager.
