### ISSUE TITLE
"Reschedule for" and "Skip" buttons

### ISSUE THREAD

**Issue by serrq** [jenspfahl/EverydayTasks#48]
Sometimes some activities are aborted or postponed, so it is necessary (in my opinion) a quick way to tell this to the app.

"Reschedule for" opens a dialog with some quick choices like "this afternoon", "this evening", "tomorrow" (at the same time), "custom", etc. 
The rescheduling action is intended once. The usual schedule is preserved.

"Skip" allows to abort a task without modifying nothing in the planner.

**Comment by jenspfahl** [comment]
There is already a skip button. It is the back-circle next to the check-icon. With that you can skip a schedule or postpone the due date.

A reschedule is also already in place. You can either click "Remind again" on the schedule card or "Remind later" in the notification.
