### ISSUE TITLE
Adding "once" between interval options

### ISSUE THREAD

**Issue by serrq** [jenspfahl/EverydayTasks#49]
For those tasks that happen once (no repetition, but I want the reminder just for this time).

![1000102694](https://github.com/jenspfahl/EverydayTasks/assets/113377431/a09d177c-3a39-4046-88a7-df087a5a02b9)

**Comment by loziniak** [comment]
similar to #21

**Comment by jenspfahl** [comment]
Shipped with v1.6.0
