### ISSUE TITLE
Priority / immediate schedules

### ISSUE THREAD

**Issue by loziniak** [jenspfahl/EverydayTasks#60]
Hi, it would be nice to be able to create a priority schedules. I often have many overdue tasks, and some of them are things I can do later (clean windows, call a friend), but some tasks should be done **immediately**, especially non-dynamic ones (pay rent, feed a cat, water flowers). These priority tasks should appear first on my list as soon as they hit _overdue_ status.

**Comment by jenspfahl** [comment]
Shipped with v1.6.0
