### ISSUE TITLE
Custom Tasks and Categories are not saved to backup

### ISSUE THREAD

**Issue by loziniak** [jenspfahl/EverydayTasks#63]
I made a backup of my database, that contained Journal entries and Schedules created from new Tasks under custom added Category. Unfortunately, after restoring the backup, Task of the Schedule is unknown.

Screenshots from source:
![obraz](https://github.com/jenspfahl/EverydayTasks/assets/5331492/51cefb25-fb9f-4e6c-a91e-63dc0d5bb8ad)
![obraz](https://github.com/jenspfahl/EverydayTasks/assets/5331492/a309ce20-3873-45c1-ac08-be9af2c85277)

And from destination:
![obraz](https://github.com/jenspfahl/EverydayTasks/assets/5331492/ca8f0325-8ec2-4f35-aaf5-842794a960ef)

Perhaps Tasks and Categories should be exported too?

**Comment by loziniak** [comment]
Oh, sorry. Categories/Tasks are ok after a phone restart.

**Comment by jenspfahl** [comment]
This is a known bug and the workaround is a simple restart of the app (swipe it off to terminate the app.) Will be fixed with the next version (coming soon).
