### ISSUE TITLE
A bug in version 1.6.0 (10600)

### ISSUE THREAD

**Issue by Lyshkam** [jenspfahl/EverydayTasks#64]
Prior to this version, I could complete tasks early. That is, I could checkmark a scheduled task as 'done' a half-hour before it was due, and the task would be complete for today and move to the next scheduled due date.

Since this version, if I checkmark a scheduled task early, it creates a diary entry, but the task remain 'due today' on the schedule, and I have to press 'skip due date' for it to move to the next scheduled due date.

**Comment by jenspfahl** [comment]
Thanks for flagging this. I assume you mean "Fixed" schedules. 
The reason why I changed this behavior is that before you could create a diary entry and the schedule moved forward without any notice. If you create 3 diary entries in a row it would move 3 times forward far in the future. To limit confusion I decided to only move forward as long as the schedule is already due.
But I understand your point and can add an option in the settings to opt-in to the old behavior.

**Comment by Lyshkam** [comment]
Correct. I wasn't familiar with the term "Fixed" schedules because I hadn't created any new tasks since the update.

If I might make a suggestion, perhaps creating a diary entry from the journal tab doesn't advance the schedule, but creating a diary entry from the ✓ on the schedules tab does mark that occurrence complete and advance the schedule.

Maybe it's not quite that simple, but that seems to convey the intent of 'this scheduled task is complete even though it isn't due yet'. Having it as an option in the settings would work fine for me too. Thank you.

**Comment by jenspfahl** [comment]
That's a good suggestion! Will consider this, thanks.

**Comment by Lyshkam** [comment]
As of the update this morning, completing tasks early now works as I would expect. Thanks.
