### ISSUE TITLE
Notifications don't work.

### ISSUE THREAD

**Issue by Martoris** [jenspfahl/EverydayTasks#65]
I don't get any notification from the app. Authorization granted and enabled in settings.
I'm using the latest build available on f droid 1.6.1

**Comment by jenspfahl** [comment]
Have you enabled notifications? On the "Schedules" page is an icon (https://everydaytasks.jepfa.de/img/notifications_enabled_icon.png) for that.

**Comment by Martoris** [comment]
> Have you enabled notifications? On the "Schedules" page is an icon (https://everydaytasks.jepfa.de/img/notifications_enabled_icon.png) for that.

Yes

**Comment by Martoris** [comment]
Sorry miss click
Notif are enable on android parameters and on the app

**Comment by Martoris** [comment]
😭😭😭 really sorry I don't really know github

**Comment by Martoris** [comment]
Ok i think i have understood 
Sincerely sorry
Is it possible to clean my error for delete the spam ?
