### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Quantum-Future** [jenspfahl/EverydayTasks#68]
[EverydayTasks_es.json](https://github.com/jenspfahl/EverydayTasks/files/15140449/EverydayTasks_es.json)

Hi, I think it's a great app, so I decided to translate it into spanish.
I attached the translated file.

**Comment by jenspfahl** [comment]
Hi, i am working an a new version. Could you please translate these phrases to spanish? Thanks!

```
"remind_before_description": "Choose in-advance reminder",
"remind_before": "{when} before",
```

```
    "pre_notification": {
          "title_normal_task": "Scheduled task is due soon",
          "title_fixed_task": "Scheduled fixed task is due soon",
          "message_normal_task": "Scheduled task '{title}' is due in {when}.",
          "message_fixed_task": "Scheduled fixed task '{title}' is due in {when}."
    },
```

```
"move_task_down": {
          "title": "Transform task to variant",
          "message": "To which task shall the transformed variant belong to?",
          "success": "Task with name '{title}' transformed to variant"
        },
```
```

"move_variant_up": {
          "success": "Variant with name '{title}' transformed to task"
        },
```

**Comment by Quantum-Future** [comment]
Yes, no problem, I'll do it tomorrow.

**Comment by Quantum-Future** [comment]
Here it is:




```
"remind_before_description": "Elija recordatorio por adelantado",
"remind_before": "{when} antes",

```
    "pre_notification": {
          "title_normal_task": "La tarea programada vence próximamente",
          "title_fixed_task": "La tarea fija programada vence próximamente",
          "message_normal_task": "La tarea programada '{title}' vence en {when}.",
          "message_fixed_task": "La tarea fija programada '{title}' vence en {when}."
    },

```
"move_task_down": {
          "title": "Transformar tarea en variante",
          "message": "¿A qué tarea pertenecerá la variante transformada?",
          "success": "La tarea con nombre '{title}' fue transformada en una variante"
        },
```


```
"move_variant_up": {
          "success": "La variante con nombre '{title}' fue transformada en tarea"
        },
```

**Comment by jenspfahl** [comment]
Integrated in v1.7.0

**Comment by Quantum-Future** [comment]
I noticed some problems in the translated app:

A) 2 or 3 words that when viewed in the context of the app, are not very clear.
    I'll correct it with better ones, so the meaning is clearer.

B) In the Schedules page, at top is a summary with the status of scheduled tasks.
    In English the verb is put first: "1 running schedule, 0 due... "
    In Spanish, the verb ("activa") should go second: "1 tarea agendada activa, 0..."
    But the app is not considering this change of order, and shows: "1 activa tarea agendada, 0...", wich sounds weird in spanish.
    I guess the same problem happens when selecting French.
    Is it too complicated to change that?

**Comment by jenspfahl** [comment]
Ah ok. Didn't know this. One possible solution could be to add a new translation key-value pair for this phrase. 
Is it only this one?

**Comment by Quantum-Future** [comment]
I only found this case until now, but maybe there are others.

**Comment by Quantum-Future** [comment]
To make the corrections I mentioned in the first point (A), do I have to wait for you to add the translation key-value pairs?

**Comment by jenspfahl** [comment]
You mean your point B, the problem with the twisted wording? For that I'll create a new key  when I get the time for it 😉.
For point A, you can just send me the corrected words.
