### ISSUE TITLE
Feature request: Open app in schedules view

### ISSUE THREAD

**Issue by dontlaugh** [jenspfahl/EverydayTasks#7]
Great app 👍

I use it exclusively for recurring scheduled tasks.

Completing a task takes me to the journal. That's cool! But I usually close the app immediately and come back later. When I come back, hours later, I would like to be looking at my schedule.

My workflow will be different from others, so if you do this at all, it should be a configuration option.

**Comment by jenspfahl** [comment]
Hi and thanks for your suggestion. Yes, i also thought about that kind of workflow. I think I will add a pin-icon on top of the schedules page similar to QuickAdd to toggle starting the app with this page. Expect it in version 1.1.0 in some weeks.
