### ISSUE TITLE
Option for not recording a schedule in the Journal

### ISSUE THREAD

**Issue by Quantum-Future** [jenspfahl/EverydayTasks#72]
There are some scheduled tasks that I don't need to log them in the journal; only be reminded of due date/time, but not save them to journal.
This could be achieved by adding a checkbox "Save to journal" (or similar) when creating a schedule.
By default the checkbox is marked, so if you want to not save a particular schedule, you clear the checkbox. (Maybe the logic could be the opposite if you prefer).

**Comment by jenspfahl** [comment]
To reset a schedule without creating a journal entry just click on the right icon close to the ✔️-icon. By doing this, the progress bar is reset and you will receive the next notification once the schedule is due again.
