### ISSUE TITLE
Wrong schedule date, when adding journal entry in the past.

### ISSUE THREAD

**Issue by loziniak** [jenspfahl/EverydayTasks#73]
For a monthly flexible task, which was due 10 days ago, when I create a journal from it (a "tickmark" icon) and select, that it was done 7 days ago, it gets scheduled 1 month **from now**, instead from 7 days ago (which is ~23 days from now).

It's in version 1.6.1

**Comment by jenspfahl** [comment]
Should be fixed with 1.7.0
