### ISSUE TITLE
Getting no notifications

### ISSUE THREAD

**Issue by stevenxxiu** [jenspfahl/EverydayTasks#78]
I've used this app for a while but never got any notifications.

I have *Settings* -> `Apps` -> *Everyday Tasks* -> ` Permissions` with notifications allowed.

I also have the bell icon enabled in *Everyday Tasks* -> `Schedules`.

Other apps appear to give me notifications fine.

**Comment by jenspfahl** [comment]
That's unfortunate. Do the single schedules also have the bell icon / reminder activated? Which version of the app and which Android version do you use?

**Comment by stevenxxiu** [comment]
What do you mean about single schedules? Could you give me a screenshot? 

I'm on *Everyday Tasks* v1.7.0, *Android* 14.

**Comment by jenspfahl** [comment]
![Screenshot_20240714-113252.png](https://github.com/user-attachments/assets/ac9f6467-012b-46af-bb9f-93473743cac7)

When you edit a schedule you can activate or deactivate the reminder. 


Also, does a notification occur when you start tracking?

**Comment by stevenxxiu** [comment]
Thanks, it worked when I edited it!
