### ISSUE TITLE
Schedule Reminders not Working?

### ISSUE THREAD

**Issue by MichaelDevon** [jenspfahl/EverydayTasks#79]
I set a schedule to every few days. It was overdue because i didnt get a notification. For testing i set remind again to 1 minutes and pressed remind again.
Still no notification appeared. Am i doing something wrong? Notifcation access is enabled in permissions.

**Comment by jenspfahl** [comment]
I would kindly refer to https://github.com/jenspfahl/EverydayTasks/issues/78.

Please let me know whether or not this solves your issue.

**Comment by jenspfahl** [comment]
And the bell-icon on top of the Schedules page is not crossed out? 
It shouldn't matter if the app is killed by the OS, notifications should work anyway.

**Comment by jenspfahl** [comment]
Does a notification occur when you start a tracking of a task? 
The app uses two different notification types for 
A) tracking of tasks
B) due schedules

Both can be activated or deactivated in the notification settings of the OS.

**Comment by jenspfahl** [comment]
I just tested again with the remind again function like you did and it works at least for me. So you never received any notification from the schedules? Neither from the predefined tasks nor from a custom?

**Comment by jenspfahl** [comment]
Yes, there should appear a notification. All looks well in your recording. I'll try to reproduce it tomorrow with my test phone from scratch. I cannot see what's wrong unfortunately. 

Thanks for letting me know. Will try to figure out what's wrong.

**Comment by jenspfahl** [comment]
Hey, I could reproduce the issue and was able to identify the problem. I am fixing it during the next few days with a new version.

**Comment by jenspfahl** [comment]
Fixed with v1.7.2
