### ISSUE TITLE
File format plain text?

### ISSUE THREAD

**Issue by gooddadmike** [jenspfahl/EverydayTasks#80]
I love this app but wondered if the file format is human readable (plain text, mardown or easily readible json variant)?

**Comment by jenspfahl** [comment]
Do you mean the backup file? This is a SQLite file containing all data in different tables. I assume you can open it with any sqlite client.

**Comment by gooddadmike** [comment]
I was asking if the format would be easily readable in a plain text file. Thank you for clarifying
