### ISSUE TITLE
Only show today's "Due later"

### ISSUE THREAD

**Issue by MartyLake** [jenspfahl/EverydayTasks#81]
Hello,
Is there an option to hide "Due later" section by default? I have tasked scheduled everyday but it doesn't make sense to me to see that I have to do that task in 23 hours.
Or better yet, maybe there could be a due today section that contains due tasks for today ?

Best,

**Comment by jenspfahl** [comment]
Hi! 
You can get a Today- and Tomorrow-section if you sort the schedules "by remaining time" and not "by progress". Because "by progress" sorts by the progress bar value and here I don't know any days. 
I hope that helps.

**Comment by MartyLake** [comment]
Thanks! The settings you mentionned solves my issue. thanks!

**Comment by loziniak** [comment]
The hybrid view (issue #24) would solve this also.
