### ISSUE TITLE
Due date always reverts to different date when creating schedule with custom interval

### ISSUE THREAD

**Issue by miguelsvieira** [jenspfahl/EverydayTasks#83]
Hi there,

When I create a fixed schedule with custom interval ("every 3 weeks") and a specific due date in the future, the due date is always changed to a different one than the one I picked. This only seems to happen when the recurring week day for the schedule is the same as or "higher" than the current week day (for instance, if today is a Friday, the bug will manifest when I create a recurring schedule for Saturdays, but not if the recurring week day is Thursdays). The bug also seems to manifest when I try to edit the schedule in question.

I'm getting this behavior in v1.7.2, but it was probably there in a few previous versions (I am only reporting now but noticed this bug some months ago).

Let me know if you need more info, and thanks for the great app!

**Comment by jenspfahl** [comment]
Thanks for reporting this bug!
The bug seems to appear only for week-based fixed schedules. 
I am looking into it and will try to come up with a fix soon.

**Comment by jenspfahl** [comment]
Fixed with v1.7.3
