### ISSUE TITLE
Feature request: set default duration for journal entries

### ISSUE THREAD

**Issue by J-Reis** [jenspfahl/EverydayTasks#84]
**Feature request:** would like to be able to speed up checking off basic tasks by avoiding having to pick a duration from the menu each time. Ability to configure schedules not to require a duration or ability to set a default duration so it needed be selected each time would be a meaningful improvement for me (and possibly/hopefully others).

**Comment by jenspfahl** [comment]
You can already achieve this by using tasks in your schedules (not categories) and defining a usual duration or usual execution time at a task. For that, go to the tasks page (the task tree), select the task you use in a schedule and click the action-button and then the pencil icon. That's it.

**Comment by J-Reis** [comment]
Appreciated, thanks.
