### ISSUE TITLE
More precise schedule intervals

### ISSUE THREAD

**Issue by mkndn** [jenspfahl/EverydayTasks#9]
Thanks for the effort and hard work. 
It would be great if there's an option to select "Every Monday", "Every Tuesday" etc., under interval while creating a new schedule. 

![Screenshot_20221005-122620.jpg](https://user-images.githubusercontent.com/20502054/194027817-be693293-3f36-40d8-934f-a809c3e0f66a.jpg)

**Comment by mani0608** [comment]
Ah yes. You're right. Thanks for the suggestion. But with that approach, I may have to schedule different tasks for every day in case my schedule does follow a continuous pattern. Let’s say on Mondays and Fridays every week, my schedule is at 4PM and on other days, it's at 3 PM. In this case, I will create 5 different tasks for a week. If we have "weekday' select with "AND" and "OR" options, it would make it more user-friendly.

**Comment by jenspfahl** [comment]
With the Dynamic Repetition Mode set to disabled I could imagine this feature. Thanks for the link to Habitica, when I get the time I will try to add this feature.

**Comment by mkndn** [comment]
I decided to create one myself for my personal use. Thanks for your support and hard work. Really appreciate it 🙏
